### ISSUE TITLE
Cannot create nested generic interfaces

### ISSUE THREAD

**Issue by Nylle** [Nylle/JavaFixture#25]
Creating the object:
```
public class TestObjectWithNestedGenericInterfaces {
    private ITestGeneric<String, ITestGenericInside<Integer>> testGeneric;
    public ITestGeneric<String, ITestGenericInside<Integer>> getTestGeneric() {
        return testGeneric;
    }
}
```
fails with:
```
java.lang.InstantiationError: com.github.nylle.javafixture.testobjects.ITestGeneric
	at jdk.internal.reflect.GeneratedSerializationConstructorAccessor1.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
	at com.github.nylle.javafixture.ReflectionHelper.newInstance(ReflectionHelper.java:65)
	at com.github.nylle.javafixture.specimen.GenericSpecimen.create(GenericSpecimen.java:81)
	at com.github.nylle.javafixture.specimen.GenericSpecimen.create(GenericSpecimen.java:68)
	at com.github.nylle.javafixture.specimen.ObjectSpecimen.customize(ObjectSpecimen.java:74)
```

**Comment by Nylle** [comment]
Fixed in version 1.3.1
