### ISSUE TITLE
Charset may run into a stack-overflow under Jdk18

### ISSUE THREAD

**Issue by jk-idealo** [Nylle/JavaFixture#77]
When fixturing a class that contains a `Charset`, it is likely that it runs into a stackoverflow, because (apparently) there is a static factory method that takes a charset: `Charset.xxx(String, Charset)`. 
I was unable to confirm that for now.

**Comment by akutschera** [comment]
I can confirm that creating a fixture of a Charset will succeed with JDK17 and fail with JDK18
```
@Test
void charsetTest() {
     var charset = fixture().create(Charset.class);
     assertThat( charset ).isNotNull();
}
```
The stack trace looks similar to this (it depends on which random method is used when)
```
java.lang.StackOverflowError
	at java.base/java.util.Random.<init>(Random.java:108)
	at com.github.nylle.javafixture.PseudoRandom.<init>(PseudoRandom.java:13)
	at com.github.nylle.javafixture.specimen.PrimitiveSpecimen.<init>(PrimitiveSpecimen.java:38)
	at com.github.nylle.javafixture.SpecimenFactory.build(SpecimenFactory.java:26)
	at com.github.nylle.javafixture.InstanceFactory.manufactureOrNull(InstanceFactory.java:137)
	at com.github.nylle.javafixture.InstanceFactory.lambda$manufacture$2(InstanceFactory.java:71)
	at java.base...
	at com.github.nylle.javafixture.InstanceFactory.manufacture(InstanceFactory.java:74)
	at com.github.nylle.javafixture.specimen.AbstractSpecimen.create(AbstractSpecimen.java:51)
	at com.github.nylle.javafixture.InstanceFactory.manufactureOrNull(InstanceFactory.java:140)
	at com.github.nylle.javafixture.InstanceFactory.lambda$manufacture$2(InstanceFactory.java:71)
	at java.base...
	at com.github.nylle.javafixture.InstanceFactory.manufacture(InstanceFactory.java:74)
	at com.github.nylle.javafixture.specimen.AbstractSpecimen.create(AbstractSpecimen.java:51)
	at com.github.nylle.javafixture.InstanceFactory.manufactureOrNull(InstanceFactory.java:140)
	at com.github.nylle.javafixture.InstanceFactory.lambda$manufacture$2(InstanceFactory.java:71)
...
```

**Comment by Nylle** [comment]
I like both proposals. Would it be feasible to exclude factory methods that have their own type as arguments to prevent similar circular behaviour for other types, or do you think this is premature?

**Comment by akutschera** [comment]
I think it would be feasible. I extended the PR to include this.
Since factory methods are the last in a list of tries to construct a fixture, it does not make sense to allow factory methods that need a fixture for which we will need (potentially) the same factory method to create it, which could lead to an endless recursion.

We will now always create a defaultCharset in Java 17+, because that's the only factory method that we can successfully call. 

Creating a random charset from the list of available charsets is something for a later PR.
